# Change these first
owner: cioos-siooc # Your GitHub organization or username, where this repository lives
repo: cwatch-upptime # The name of this repository

sites:

  - name: Cioos National Wordpress
    url: https://cioos.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: Cioos National CKAN
    url: https://catalogue.cioos.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: Cioos National CKAN Sitemap
    url: https://catalogue.cioos.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: Cioos Atlantic Wordpress
    url: https://cioosatlantic.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Atlantic CKAN
    url: https://catalogue.cioosatlantic.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Atlantic CKAN Sitemap
    url: https://catalogue.cioosatlantic.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Atlantic ERDDAP
    url: https://cioosatlantic.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: St. Lawrence Global Observatory Wordpress
    url: https://ogsl.ca/en/home-slgo/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: St. Lawrence Global Observatory CKAN
    url: https://catalogue.ogsl.ca/en/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: St. Lawrence Global Observatory CKAN Sitemap
    url: https://catalogue.ogsl.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: St. Lawrence Global Observatory ERDDAP
    url: https://erddap.ogsl.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - ogsletcax

  - name: Cioos Pacific Wordpress
    url: https://cioospacific.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Pacific CKAN
    url: https://catalogue.cioospacific.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Pacific CKAN Sitemap
    url: https://catalogue.cioospacific.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Cioos Pacific ERDDAP
    url: https://data.cioospacific.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh
      - n-a-t-e

  - name: Hakai ERDDAP
    url: https://catalogue.hakai.org/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees:
      - fostermh
      - n-a-t-e

  - name: SmartAtlantic ERDDAP
    url: https://www.smartatlantic.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees:
      - sjbruce

  - name: CIOOS Pacific Dev CKAN
    url: https://catalogue.pac-dev1.cioos.org/
    maxResponseTime: 5000 # 5 seconds
    headers:
      - "Authorization: Basic $GH_CIOOS_PACIFIC_DEV_BASIC_AUTH"
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: CIOOS Data Explorer Website
    url: https://explore.cioos.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - n-a-t-e

  - name: CIOOS Data Explorer API
    url: https://explore.cioos.ca/api/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - n-a-t-e
      
  - name: CIOOS Pacific ERDDAP dataset DFO_MEDS_BUOYS
    url: https://data.cioospacific.ca/erddap/tabledap/DFO_MEDS_BUOYS.htmlTable?STN_ID&time>=now-1week&distinct()
    maxResponseTime: 10000 # 10 seconds
    assignees: # Users to assign downtime issues (optional)
      - n-a-t-e
      
  - name: CIOOS Pacific ERDDAP dataset ECCC_MSC_BUOYS
    url: https://data.cioospacific.ca/erddap/tabledap/ECCC_MSC_BUOYS.htmlTable?wmo_synop_id&time>now-3hours&distinct()
    maxResponseTime: 10000 # 10 seconds
    assignees: # Users to assign downtime issues (optional)
      - n-a-t-e


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cwatch-upptime
  logoUrl: https://raw.githubusercontent.com/cioos-siooc/ckanext-cioos_theme/master/ckanext/cioos_theme/public/base/images/logos/cioos-banner-en.png
  name: CIOOS Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/cioos-siooc/cwatch-upptim). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean
  metaTags:
  - name: "color-scheme"
    content: "dark light"
  - name: "robots"
    content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
