# Change these first
owner: cioos-siooc # Your GitHub organization or username, where this repository lives
repo: cwatch-upptime # The name of this repository

sites:

  - name: Cioos National Wordpress
    url: https://cioos.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette

  - name: Cioos National CKAN
    url: https://catalogue.cioos.ca/
    maxResponseTime: 5000 # 5 seconds
    headers:
      - "x-uptime-token: $CF_ALLOW_TOKEN"
    assignees: # Users to assign downtime issues (optional
      - jessybarrette

  - name: Cioos National CKAN Sitemap
    url: https://catalogue.cioos.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    headers:
      - "x-uptime-token: $CF_ALLOW_TOKEN"
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette
  
  - name: CIOOS-SIOOC Guide Fr
    url: https://guide.cioos.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette
      
  - name: CIOOS-SIOOC Guide En
    url: https://guide.cioos.ca/en
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette

  - name: Cioos Atlantic Wordpress
    url: https://cioosatlantic.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - sjbruce
      - JaredMclellan

  - name: Cioos Atlantic CKAN
    url: https://catalogue.cioosatlantic.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - sjbruce
      - JaredMclellan

  - name: VITALITY CKAN
    url: https://catalogue.registry.cioosatlantic.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - sjbruce
      - JaredMclellan

  - name: Cioos Atlantic CKAN Sitemap
    url: https://catalogue.cioosatlantic.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - sjbruce
      - JaredMclellan

  - name: Cioos Atlantic ERDDAP
    url: https://cioosatlantic.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - sjbruce
      - JaredMclellan

  - name: St. Lawrence Global Observatory Wordpress
    url: https://ogsl.ca/en/home-slgo/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: St. Lawrence Global Observatory CKAN
    url: https://catalogue.ogsl.ca/en/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: St. Lawrence Global Observatory CKAN Sitemap
    url: https://catalogue.ogsl.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: St. Lawrence Global Observatory ERDDAP
    url: https://erddap.ogsl.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: Cioos Pacific Wordpress
    url: https://cioospacific.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: CIOOS Pacific Wordpress Login Page
    url: https://cioospacific.ca/wp-admin/
    maxResponseTime: 5000 # 5 seconds

  - name: Cioos Pacific Applied Data - Marine Heat Waves
    url: https://cioospacific.ca/applied-data/marine-heat-monitor/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: Cioos Pacific Applied Data - Marine Heat Waves iframe Source
    url: https://hakaiinstitute.github.io/ssta_images/dist
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: Cioos Pacific CKAN
    url: https://catalogue.cioospacific.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: Cioos Pacific CKAN Sitemap
    url: https://catalogue.cioospacific.ca/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: Cioos Pacific ERDDAP
    url: https://data.cioospacific.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: SmartAtlantic ERDDAP
    url: https://www.smartatlantic.ca/erddap/index.html
    maxResponseTime: 5000 # 5 seconds
    assignees:
      - sjbruce

  - name: CIOOS Pacific Dev CKAN
    url: https://catalogue.pac-dev1.cioos.org/
    maxResponseTime: 5000 # 5 seconds
    headers:
      - "Authorization: Basic $GH_CIOOS_PACIFIC_DEV_BASIC_AUTH"
    assignees: # Users to assign downtime issues (optional)

  - name: CIOOS Data Explorer Website
    url: https://explore.cioos.ca
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette

  - name: CIOOS Data Explorer API
    url: https://explore.cioos.ca/api/organizations
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette
      
  - name: CIOOS Pacific ERDDAP dataset DFO_MEDS_BUOYS
    url: https://data.cioospacific.ca/erddap/tabledap/DFO_MEDS_BUOYS.htmlTable?STN_ID&time>=now-1week&distinct()
    maxResponseTime: 10000 # 10 seconds
    assignees: # Users to assign downtime issues (optional)
      
  - name: CIOOS Pacific ERDDAP dataset ECCC_MSC_BUOYS
    url: https://data.cioospacific.ca/erddap/tabledap/ECCC_MSC_BUOYS.htmlTable?wmo_synop_id&time>now-3hours&distinct()
    maxResponseTime: 10000 # 10 seconds
    assignees: # Users to assign downtime issues (optional)

  - name: CIOOS Metadata Entry Form Region Page
    url: https://cioos-siooc.github.io/metadata-entry-form/#/en/region-select
    __dangerous__body_down_if_text_missing: 'You need to enable JavaScript to run this app.'
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - jessybarrette

  - name: Amundsen Science CKAN
    url: https://catalogue.amundsenscience.com/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional
      - jessybarrette
      - tratsimbazafy
      
  - name: Amundsen Science ERDDAP
    url: https://erddap.amundsenscience.com/erddap
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional
      - jessybarrette
      - tratsimbazafy 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cwatch-upptime
  logoUrl: https://cioos-siooc.github.io/cwatch-upptime/cioos-national_EN.svg
  themeUrl: https://cioos-siooc.github.io/cwatch-upptime/cioos.css
  faviconSvg: https://cioos-siooc.github.io/cwatch-upptime/ICON_color.svg
  graphBackgroundColor: "#152F37"
  graphBorderColor: "#F3F0EC"
  name: ""
  introTitle: "**CIOOS** Service Status Monitor"
  introMessage: This page monitors the uptime and performance of web services for the Canadian Integrated Ocean Observing System (CIOOS) and its regional associations, including CIOOS Atlantic, CIOOS Pacific, and St. Lawrence Global Observatory. Real-time data is automatically collected from our [GitHub repository](https://github.com/cioos-siooc/cwatch-upptime) using GitHub Actions.
  navbar:
    - title: Home
      href: https://cioos.ca
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean
  metaTags:
  - name: "color-scheme"
    content: "dark light"
  - name: "robots"
    content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
